# Generated by Django 3.2.6 on 2025-05-28 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(default='new user', max_length=255)),
                ('graduacao', models.CharField(default='new user', max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('BLOCO A', 'Bloco A'), ('BLOCO B', 'Bloco B'), ('BLOCO C', 'Bloco C'), ('BLOCO D', 'Bloco D'), ('BLOCO E', 'Bloco E'), ('BLOCO F', 'Bloco F'), ('BLOCO G', 'Bloco G'), ('BLOCO H', 'Bloco H'), ('BLOCO I', 'Bloco I'), ('BLOCO J', 'Bloco J'), ('BLOCO K', 'Bloco K'), ('BLOCO L', 'Bloco L'), ('BLOCO M', 'Bloco M'), ('BLOCO N', 'Bloco N'), ('BLOCO O', 'Bloco O'), ('BLOCO P', 'Bloco P'), ('BLOCO Q', 'Bloco Q'), ('BLOCO T', 'Bloco T')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UORG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('detentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uorgs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='home.bloco')),
                ('uorg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='home.uorg')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('numero_patrimonio', models.CharField(max_length=50, unique=True)),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='home.sala')),
                ('uorg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='home.uorg')),
            ],
        ),
    ]
