# Generated by Django 3.2.6 on 2025-03-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detentor',
            name='graduacao',
        ),
        migrations.RemoveField(
            model_name='detentor',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='detentor',
            name='nome',
        ),
        migrations.AlterField(
            model_name='detentor',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
