# Generated by Django 3.2.6 on 2025-06-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloco',
            name='nome',
            field=models.CharField(choices=[('BLOCO A', 'Bloco A'), ('BLOCO B', 'Bloco B'), ('BLOCO C', 'Bloco C'), ('BLOCO D', 'Bloco D'), ('BLOCO E', 'Bloco E'), ('BLOCO F', 'Bloco F'), ('BLOCO G', 'Bloco G'), ('BLOCO H', 'Bloco H'), ('BLOCO I', 'Bloco I'), ('BLOCO J', 'Bloco J'), ('BLOCO K', 'Bloco K'), ('BLOCO L', 'Bloco L'), ('BLOCO M', 'Bloco M'), ('BLOCO N', 'Bloco N'), ('BLOCO O', 'Bloco O'), ('BLOCO P', 'Bloco P'), ('BLOCO Q1', 'Bloco Q1'), ('BLOCO Q2', 'Bloco Q2'), ('BLOCO T', 'Bloco T')], max_length=20, unique=True),
        ),
    ]
