# Generated by Django 3.2.6 on 2025-03-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20250320_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='detentor',
            name='graduacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detentor',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
