# Generated by Django 3.2.6 on 2025-07-03 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_bloco_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_transferencia', models.CharField(choices=[('pendente', 'Pendente'), ('autorizada', 'Autorizada'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('obs', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('detentor_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_destino', to=settings.AUTH_USER_MODEL)),
                ('detentor_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_origem', to=settings.AUTH_USER_MODEL)),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_gerente', to=settings.AUTH_USER_MODEL)),
                ('sala_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_sala_destino', to='home.sala')),
                ('sala_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_sala_origem', to='home.sala')),
                ('uorg_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_uorg_destino', to='home.uorg')),
                ('uorg_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_uorg_origem', to='home.uorg')),
            ],
        ),
        migrations.CreateModel(
            name='TransferenciaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_transferidos', to='home.item')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='home.transferencia')),
            ],
        ),
    ]
