# Generated by Django 3.2.6 on 2025-03-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20250320_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detentor',
            name='graduacao',
            field=models.CharField(default='new user', max_length=100),
        ),
        migrations.AlterField(
            model_name='detentor',
            name='nome',
            field=models.CharField(default='new user', max_length=255),
        ),
    ]
